Flask_projects/flask_basic/pybo/views/auth_views.py
from flask import Blueprint, render_template, request, url_for, flash, session, g
from pybo.models import  Users
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

import functools
from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm


bp = Blueprint("auth", __name__, url_prefix='/auth')

@bp.route("/signup", methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == "POST" and form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()

        if not user:
            user = Users(username=form.username.data,
                         password=generate_password_hash(form.password1.data),
                         email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash("이미 존재하는 사용자입니다.")
    return render_template("auth/signup.html", form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = Users.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = Users.query.get(user_id)

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

Flask_projects/flask_basic/pybo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
    <title>게시판</title>

</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}

    <script src="{{url_for('static', filename='jquery-3.7.1.min.js')}}"></script>
    <script src="{{url_for('static', filename='bootstrap.min.js')}}"></script>

{% block script %}
{% endblock %}
</body>
</html>

Flask_projects/flask_basic/pybo/templates/form_errors.html
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
  <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}

{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
  {{ message }}
</div>
{% endfor %}

Flask_projects/flask_basic/pybo/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class = "navbar-brand" href="{{ url_for('main.index')}}">Bulletin</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        {% if g.user %}
        <ul class ="navbar-nav">
            <il class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">로그아웃</a>
            </il>
        </ul>
        {% else %}
        <ul class ="navbar-nav">
            <il class="nav-item">
                <a class="nav-link" href="{{url_for('auth.signup')}}">계정생성</a>
            </il>
            <il class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">로그인</a>
            </il>
        </ul>
        {% endif %}
    </div>
</nav>
</body>
</html>