Flask_projects/flask_basic/pybo/views/answer_views.py
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect
from datetime import datetime
from ..forms import AnswerForm

from pybo import db
from pybo.models import Question, Answer
from pybo.views.auth_views import login_required



bp = Blueprint("answer", __name__, url_prefix='/answer')

@bp.route("/create/<int:question_id>", methods=('GET', 'POST'))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))

    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))

    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            return redirect('{}#answer_{}'.format(
                url_for('question.detail', question_id=answer.question.id), answer.id
            ))
    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', answer=answer, form=form)

@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

# @bp.route('/detail/', methods=['GET', 'POST'])
# def indexAnswer():
#     targetNum = request.args.get("question_id", type=int)
#     answer_list = Answer.query.filter(Answer.question_id==targetNum).all()
#     return render_template('answer/answer_list.html', answer_list=answer_list)

Flask_projects/flask_basic/pybo/views/question_views.py
from flask import Blueprint, render_template, request, redirect, url_for, g, flash
from pybo.models import Question
from ..forms import QuestionForm, AnswerForm
from datetime import datetime


from pybo import db

from pybo.views.auth_views import login_required

bp = Blueprint("question", __name__, url_prefix='/question')


@bp.route("/hello")
def hello_pybo():
    return "hello, pybo!"

@bp.route('/list')
def _list():
    page = request.args.get('page', type=int, default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page=page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list)

@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    form = QuestionForm()

    if request.method == 'POST' and form.validate_on_submit():
        print("그런 아침, 그런 생각, POST")
        question = Question(
            subject=form.subject.data,
            content=form.content.data,
            create_date=datetime.now(),
            user=g.user
        )
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('question/question_form.html', form=form)

@bp.route("/modify/<int:question_id>", methods=('GET','POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)

@bp.route("/delete/<int:question_id>")
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    # answer_list = Answer.query.filter(Answer.question_id==question_id).all()
    return render_template('question/question_detail.html', question=question, form=form)

Flask_projects/flask_basic/pybo/templates/question/question_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap.min.css')}}">
</head>
<body>
<div class = "container my-3">
    <h2 class="bprder-bottom py-2"> {{ question.subject }} </h2>
    <div class="card-body">
        <div class="card-text" style="white-space: pre-line"> {{ question.content }} </div>
        <div class="text-end">
            <div class="badge badge-light text-dark p-2">
                <div class="mb-2">{{ question.user.username }}</div>
                <div>{{ question.create_date }}</div>
            </div>

        </div>
    </div>
    {% if g.user == question.user %}
    <div>
        <a href="{{url_for('question.modify', question_id=question.id)}}"
        class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="{{url_for('question.delete', question_id=question.id)}}"
        class="delete btn btn-sm btn-outline-secondary"
        data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
    </div>
    {% endif %}
</div>


<h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }} 개의 답변이 있습니다.</h5>


    {% if question.answer_set %}
        <div>
            {% for answer in question.answer_set %}
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;"> {{ answer.content or '' }}</div>
                    <div class="text-end">
                        <div class="badge bg-light text-dark p-2">
                            <div class="mb-2">{{ answer.user.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                </div>
                {% if g.user == answer.user %}
                <div class="my-3">
                    <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                    class="btn btn-sm btn-outline-secondary">수정</a>

                    <a href="{{ url_for('answer.delete', answer_id=answer.id) }}"
                    class="btn btn-sm btn-outline-secondary">삭제</a>

                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p>답변이 없습니다.</p>
    {% endif %}

    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{form.csrf_token}}
        {% for field, errors in form.errors.items() %}
            <div class="alert alert-danger" role="alert">
                <strong> {{ form[field].label }} </strong>: {{ ','.join(errors) }}
            </div>
        {% endfor %}
        <div class="form-group">
            <textarea {% if not g.user %}disabled{% endif %}
                name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>

    {% block script %}
    <script type='text/javascript'>
        $(document).ready(function()){
            $(".delete").on('click', function()){
                if(confirm("정말로 삭제하시겠습니까?")){
                    location.href = $(this).data('uri');
                }
            };
        };
    </script>
    {% endblock %}
</body>
</html>

Flask_projects/flask_basic/pybo/templates/question/question_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="my-3">
        {{ form.csrf_token }}
        {% for field, errors in form.errors.items() %}
            <div class="alert alert-danger" role="alert">
                <strong> {{ form[field].label }}</strong>:{{ ','.join(errors) }}
            </div>
        {% endfor %}
        <div class="mb-3">
<!--            {{ form.subject.label(class="form-label") }}-->
<!--            {{ form.subject(class="form-control") }}-->
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" value="{{form.content.data or ''}}">
        </div>

        <div class="mb-3">
<!--            {{ form.content.label(class="form-label") }}-->
<!--            {{ form.content(class="form-control", rows="10") }}-->
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{form.subject.data or ''}}</textarea>
        </div>

        <button type="submit" class="btn btn-primary mt-3">저장하기</button>
    </form>
  </div>
{% endblock %}
</body>
</html>

Flask_projects/flask_basic/pybo/templates/question/question_list.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap.min.css')}}">
</head>
<body>

{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thread-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %}
            {% for question in question_list.items %}
            <tr>
                <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
                <td>
                <a href="{{ url_for('question.detail', question_id=question.id) }}" > {{question.subject}} </a>
                </td>
                <td>{{ question.user.username }}</td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
                <p>질문이 없습니다.</p>
        {% endif %}
        </tbody>
    </table>

    <ul class="pagination justify-content-center">
        {% if question_list.has_prev %}
        <il class=page-item"">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
        </il>
        {% else %}
        <il class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </il>
        {% endif %}

        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                    <il class=page-item"">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </il>
                    {% else %}
                    <il class="page-item activate" aria-current="page">
                        <a class="page-link" href="#">{{ page_num }}</a>
                    </il>
                {% endif %}
            {% else %}
                <il class="disabled" aria-current="page">
                    <a class="page-link" href="#">...</a>
                </il>
            {% endif %}
        {% endfor %}

        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{question_list.next_num}}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"></a>
        </li>
        {% endif %}
    </ul>

    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}
</body>
</html>